'\" t
.\"     Title: zshrc
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/12/2017
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ZSHRC" "1" "06/12/2017" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zshrc \- Zsh configuration as a zplug plugin\&.
.SH "VERSION"
.sp
0\&.0\&.0
.SH "DESCRIPTION"
.sp
This configuration system works as a meta\-plugin: all desired Zsh plugins are loaded from packages\&.zsh using zplug\&. Overall configuration then follows a normal plugin structure\&.
.sp
This document concerns the details of this specific Zsh environment\&. For installation instructions and development information, see https://github\&.com/makenew/zshrc\&.
.sp
Update this and all plugins with the included zshupg command\&.
.SH "STRUCTURE"
.sp
All packages are loaded in packages\&.zsh using zplug\&. Environment variables exported in env\&.zsh are set before loading any plugins\&.
.SH "AUTHOR"
.sp
This plugin is authored by Evan Sosenko\&.
.SH "RESOURCES"
.sp
Find the source and latest version at https://github\&.com/makenew/zshrc\&.
.SH "SEE ALSO"
.sp
zplug(1)
.SH "LICENSE"
.sp
This Zsh configuration is licensed under the MIT license: https://github\&.com/makenew/zshrc/blob/master/LICENSE\&.txt\&.
.SH "WARRANTY"
.sp
This software is provided by the copyright holders and contributors "as is" and any express or implied warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose are disclaimed\&. In no event shall the copyright holder or contributors be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage\&.
